/**
 * Mechanical authoring lints — Hugo/shortcode edition.
 *
 * Retargeted from the old site's scripts/lints.mjs (MDX/JSX) to Hugo Markdown +
 * shortcodes. The math/array/table rules are syntax-agnostic (they scan the raw
 * math, identical in both worlds) and carry over unchanged. The component rules
 * now read `{{< fillin >}}` / `{{< multiplechoice >}}` / `{{< graphplot >}}`
 * instead of `<FillIn/>` etc. MDX-only rules are dropped: a literal `{` in prose
 * is harmless in Hugo (only `{{` starts a shortcode), and the hand-written-grid
 * SVG rule is moot because every figure is generated by graph-core through the
 * converter.
 *
 * lintHugo(src, filename?) → { errors, warnings }  (zero dependencies)
 */

const lineOf = (src, index) => src.slice(0, index).split('\n').length;

/** Parse the named params of a `{{< name … >}}` shortcode opening tag body. */
function shortcodeParams(body) {
  const p = {};
  for (const m of body.matchAll(/(\w+)="([^"]*)"/g)) p[m[1]] = m[2];
  return p;
}

/** Iterate every shortcode of `name`: yields { params, inner, index }. */
function* shortcodes(src, name, paired) {
  const openRe = new RegExp(`\\{\\{<\\s*${name}\\b([\\s\\S]*?)>\\}\\}`, 'g');
  let m;
  while ((m = openRe.exec(src)) !== null) {
    let inner = '';
    if (paired) {
      const closeRe = new RegExp(`\\{\\{<\\s*/${name}\\s*>\\}\\}`, 'g');
      closeRe.lastIndex = openRe.lastIndex;
      const c = closeRe.exec(src);
      if (c) inner = src.slice(openRe.lastIndex, c.index);
    }
    yield { params: shortcodeParams(m[1]), inner, index: m.index };
  }
}

export function lintHugo(src, filename = '') {
  const errors = [];
  const warnings = [];
  const err = (i, msg) => errors.push(`L${lineOf(src, i)}: ${msg}`);
  const wrn = (i, msg) => warnings.push(`L${lineOf(src, i)}: ${msg}`);

  // ---- Math / array rules (syntax-agnostic — same in MDX and Hugo) ---------

  // \dfrac forces displaystyle sizing and crowds adjacent rows.
  for (const m of src.matchAll(/\\dfrac/g)) {
    err(m.index, '\\dfrac is banned — use \\tfrac (or \\cfrac for nested display fractions)');
  }
  // plain \frac inside a $$ array renders full-height too.
  for (const m of src.matchAll(/\\begin\{array\}[\s\S]*?\\end\{array\}/g)) {
    const inner = m[0].match(/(?<![tcd])\\frac/);
    if (inner) err(m.index + inner.index, '\\frac inside \\begin{array} — use \\tfrac so rows stay compact');
  }
  // KaTeX rejects the array-package @{…} column separator.
  for (const m of src.matchAll(/\\begin\{array\}\{[^}]*@[^}]*\}/g)) {
    err(m.index, 'array column spec uses @{…} — KaTeX does not support it; use a plain spec like {rl} or {rrl}');
  }
  // {lrcl} step arrays need \\[4pt]+ between steps.
  for (const m of src.matchAll(/\\begin\{array\}\{lrcl\}([\s\S]*?)\\end\{array\}/g)) {
    for (const s of m[1].matchAll(/\\\\(\[([\d.]+)pt\])?/g)) {
      if (!m[1].slice(s.index + s[0].length).trim()) continue; // trailing \\
      if (!s[1] || +s[2] < 4) {
        err(m.index + s.index, `{lrcl} step array row separator ${JSON.stringify(s[0])} — use \\\\[4pt] (or more)`);
      }
    }
  }
  // Unicode superscript minus can't parse as an exponent.
  for (const m of src.matchAll(/⁻/g)) {
    err(m.index, 'unicode superscript minus — write a braced exponent like 10^{-3}');
  }
  // <br/>-joined math spans in a table cell wrap mid-equation.
  {
    let offset = 0;
    for (const line of src.split('\n')) {
      if (line.includes('|') && /<br\s*\/?>/.test(line) && /\$[^$]/.test(line)) {
        err(offset, 'table cell joins math spans with <br/> — use one $\\begin{aligned}…\\end{aligned}$ span');
      }
      offset += line.length + 1;
    }
  }
  // Hotlinked images: figures must be local.
  for (const m of src.matchAll(/!\[[^\]]*\]\(\s*https?:|<img[^>]*src="https?:/g)) {
    err(m.index, 'hotlinked image — recreate the figure or describe it in prose');
  }

  // ---- fillin shortcode rules ----------------------------------------------
  for (const { params, index } of shortcodes(src, 'fillin')) {
    const where = `fillin (${(params.question || '?').slice(0, 40)}…)`;
    if (params.answer && /\^-/.test(params.answer)) {
      err(index, `${where}: answer has an unbraced negative exponent — write 10^{-3}, never 10^-3`);
    }
    if (/\\ne(?:q)?\b/.test(params.answer || '')) {
      err(index, `${where}: answer is a true/false statement (contains \\neq) — ungradeable; ask for a value or use multiplechoice`);
    }
    const q = params.question || '';
    if (/\(a\)/.test(q) && /\(b\)/.test(q)) wrn(index, `${where}: question looks multi-part ("(a)…(b)") — split into one exercise per part`);
  }

  // ---- multiplechoice shortcode rules --------------------------------------
  const graphAnswerIndexes = [];
  for (const { params, inner, index } of shortcodes(src, 'multiplechoice', true)) {
    const q = params.question || '';
    if (params.mode === 'graph') {
      if (params.answerIndex == null || params.answerIndex === '') {
        err(index, 'multiplechoice(graph): missing answerIndex');
      } else {
        const nOpts = inner.split('===OPT===').filter((s) => s.trim()).length;
        if (Number(params.answerIndex) >= nOpts) err(index, `multiplechoice(graph): answerIndex ${params.answerIndex} but only ${nOpts} option(s)`);
        graphAnswerIndexes.push({ index, n: Number(params.answerIndex) });
      }
    } else {
      const opts = inner.split('\n').map((s) => s.trim()).filter(Boolean);
      if (params.answer != null && opts.length && !opts.includes(params.answer)) {
        err(index, `multiplechoice: answer ${JSON.stringify(params.answer.slice(0, 40))} is not one of the options (exact string match required)`);
      }
    }
    if (/\(a\)/.test(q) && /\(b\)/.test(q)) wrn(index, `multiplechoice (${q.slice(0, 40)}…): question looks multi-part — split it`);
  }
  if (graphAnswerIndexes.length >= 2 && new Set(graphAnswerIndexes.map((x) => x.n)).size === 1) {
    wrn(graphAnswerIndexes[0].index, `all ${graphAnswerIndexes.length} graph multiplechoice(s) use answerIndex=${graphAnswerIndexes[0].n} — vary the correct position`);
  }

  // ---- graphplot shortcode rules -------------------------------------------
  for (const { params, inner, index } of shortcodes(src, 'graphplot', true)) {
    if (!params.ariaLabel) err(index, 'graphplot: missing ariaLabel — describe the empty grid in prose');
    let cfg = null;
    try { cfg = JSON.parse(inner.trim()); } catch { err(index, 'graphplot: inner config is not valid JSON'); }
    if (cfg && (cfg.answer == null || typeof cfg.answer !== 'object')) {
      err(index, 'graphplot: answer must be an object — {slope,intercept}, {x}, {y}, {system:[…]} or {quadratic:{…}}');
    }
  }

  // ---- Knowledge Check page rule -------------------------------------------
  if (/knowledge-check-\d+-\d+\.md$/.test(filename)) {
    for (const m of src.matchAll(/\bhint="/g)) {
      err(m.index, 'hint on a Knowledge Check — quizzes never have hints; delete the attribute');
    }
  }

  return { errors, warnings };
}
